### ISSUE TITLE
作者nb

### ISSUE THREAD

**Issue by ly886** [wcomaqsw/indulge-in-study#3]
nb啊

**Comment by ly886** [comment]
308018010 01
0 0

是我的输入有问题么

**Comment by wcomaqsw** [comment]
反映的问题我看到了，我刚刚重新更新了代码，原先有点点不足。我是检测网络条件不好后，直接推荐重新启动程序。现在可以支持循环。至于你说的返回消息的问题，实际上每个操作都是做了，我认为这种错误信息比较重要，我才显示在命令行里，其他一些比如选课的状态信息，我设置等级为debug等级，放进了你文件同目录的.log文件里面。如果选课成功也会有显示在命令行内。
**请文明使用这个程序，仅作为学习和交流的用途，不要为其他同学带来影响**
**间隔时间可以改大，但是千万别改小了，我默认10s，够你使用了，频率太高作用不大，也会给服务器带来不必要的负载**

**Comment by wcomaqsw** [comment]
你的输入是正确的，符合规范。

**Comment by ly886** [comment]
ok 我一开始以为是输入出了问题 一直没有反回结果 比如说：正在抢课中。。。这种提示 谢谢
