### ISSUE TITLE
麻烦修改一下描述，请不要在关键字中出现四川大学ok？

### ISSUE THREAD

**Issue by kongminhao** [wcomaqsw/indulge-in-study#4]
我们不反对开源，只是麻烦您注意一点， 给后来的计软学生留一点自己写的空间？

**Comment by kongminhao** [comment]
![](http://ofqm89vhw.bkt.clouddn.com/7fc73fe6d376974ed34c9a0218a5af43.png)

**Comment by wcomaqsw** [comment]
可以，谢谢提醒。提升空间的话，还有很多地方没有完善，只是一个简单能完成任务的程序，整体代码风格也没完全符合PEP8，业务逻辑设计还比较混乱。欢迎fork，只为提供一个思路
